os: linux
language: node_js
node_js: 14

jobs:
  include:
    - stage: test
      install: yarn
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - yarn build
        - yarn test:report
      after_script:
        - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      workspaces:
        create:
          name: shared
          paths:
            - node_modules
            - packages

    - stage: release
      if: branch = master AND type != pull_request
      workspaces:
        use: shared
      install: skip
      script: yarn release
