export {
  accessRightsEndpoints,
  accountEndpoints,
  starEndpoints,
  defaultStarEndpoints,
  attentionSetEndpoints,
  reviewerEndpoints,
  changeEndpoints,
  changeEditEndpoints,
  revisionEndpoints,
  revisionReviewerEndpoints,
  configEndpoints,
  documentationSearchEndpoints,
  groupEndpoints,
  groupMemberEndpoints,
  subgroupEndpoints,
  pluginEndpoints,
  projectEndpoints,
  branchEndpoints,
  commitEndpoints,
  childProjectEndpoints,
  dashboardEndpoints,
  labelEndpoints,
  tagEndpoints,
} from '@gerritkit/generator'
